[2020-07-30 03:43:27.900403] INFO: zipline.data.bundles.core: Ingesting ftx.
Traceback (most recent call last):
  File "/home/jare/.local/bin/zipline", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jare/.local/lib/python2.7/site-packages/zipline/__main__.py", line 389, in ingest
    show_progress,
  File "/home/jare/.local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 443, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/home/jare/.local/lib/python2.7/site-packages/zipline/data/bundles/csvdir.py", line 94, in ingest
    self.csvdir)
  File "/home/jare/.local/lib/python2.7/site-packages/zipline/data/bundles/csvdir.py", line 138, in csvdir_bundle
    for item in os.listdir(ddir)
OSError: [Errno 2] No such file or directory: '/home/jare/token_visualizer/m'
